#!/bin/bash

set -e

rm -f tmp/pids/server.pid

if [ ! -f "/opt/app-root/src/hitobito/Wagonfile" ]; then
  echo "⚙ Creating Wagonfile"
  cp /opt/app-root/src/Wagonfile.dev /opt/app-root/src/hitobito/Wagonfile
  echo "✅ Created Wagonfile"
else
  echo "↪️  Leaving existing Wagonfile as it is"
fi

echo "Running bundle install"
bundle install

echo "Running yarn install"
bundle exec rails webpacker:yarn_install

echo "⚙️  Testing DB connection"
timeout 300s waitfortcp "${RAILS_DB_HOST-db}" "${RAILS_DB_PORT-3306}"
echo "✅ DB server is ready"

if [ -z "$SKIP_RAILS_MIGRATIONS" ]; then
  echo "⚙️  Performing migrations"
  bundle exec rails db:migrate wagon:migrate
  echo "✅ Migrations done"
fi

echo "➡️ Handing control over to '$*''"

echo "⚙️  Executing: $@"
exec bundle exec "$@"
