#!/bin/bash

set -e

if [ ! -f "./Wagonfile" ]; then
  echo "⚙ Creating Wagonfile"
  /opt/app-root/src/hitobito/bin/active_wagon.rb core
  echo "✅ Created Wagonfile"
else
  echo "↪️  Leaving existing Wagonfile as it is"
fi

if [ -f "/opt/app-root/src/hitobito/.envrc" ]; then
  direnv allow /opt/app-root/src/hitobito/.envrc
  eval "$(direnv export bash)"
fi

echo "Running bundle install"
bundle install

echo "⚙️  Testing DB connection"
timeout 300s waitfortcp "${RAILS_DB_HOST-db}" "${RAILS_DB_PORT-3306}"
echo "✅ DB server is ready"

if [ -z "$SKIP_RAILS_MIGRATIONS" ]; then
  echo "⚙️  Performing migrations"
  bundle exec rails db:migrate wagon:migrate
  echo "✅ Migrations done"
fi

echo "➡️ Handing control over to '$*''"

echo "⚙️  Executing: $@"
exec bundle exec "$@"
