#!/bin/bash

set -e

rm -f tmp/pids/server.pid

if [ ! -f "/usr/src/app/hitobito/Wagonfile" ]; then
  echo "⚙ Creating Wagonfile"
  cp /usr/src/app/Wagonfile.dev /usr/src/app/hitobito/Wagonfile
  echo "✅ Created Wagonfile"
else
  echo "↪️  Leaving existing Wagonfile as it is"
fi

echo "Running bundle install"
bundle install

echo "Running yarn install"
bundle exec rails webpacker:yarn_install

echo "➡️ Handing control over to '$*''"

echo "⚙️  Executing: $@"
exec bundle exec "$@"
