#!/bin/bash

if [ ! -f /shared/.env.generated ]; then
  echo ".env.generated hasn't been generated by the rails container. Restarting nextcloud in 5 seconds in order to attempt again..."
  sleep 5
  exit 1
fi

set -o allexport
source /shared/.env.generated
set +o allexport

if php occ list | grep maintenance:install; then
  # Set up an admin account
  php occ maintenance:install --admin-user='admin' --admin-pass='hito42bito'
else
  # Re-apply some app state which can't easily be stored in docker volumes,
  # in case we have used docker compose down.
  php occ maintenance:update:htaccess
fi

# Activate debug logging for development
php occ config:system:set loglevel --value=0

# Disable some clutter which we don't need
php occ app:disable dashboard
php occ app:disable firstrunwizard

# Install the OIDC plugin
php occ app:install user_oidc
php occ user_oidc:provider hitobito --clientid="$NEXTCLOUD_OIDC_CLIENT_ID" --clientsecret="$NEXTCLOUD_OIDC_CLIENT_SECRET" --discoveryuri="http://localhost:3000/.well-known/openid-configuration" --scope="openid email nextcloud" --mapping-uid=sub --mapping-display-name=name --check-bearer=0 --send-id-token-hint=0
php occ config:app:set user_oidc provider-1-mappingGroups --value=groups
php occ config:app:set user_oidc provider-1-uniqueUid --value=0
php occ config:app:set user_oidc provider-1-providerBasedId --value=0
php occ config:app:set user_oidc provider-1-groupProvisioning --value=1
php occ config:app:set user_oidc provider-1-checkBearer --value=1
php occ config:app:set user_oidc provider-1-bearerProvisioning --value=0
php occ config:app:set user_oidc provider-1-sendIdTokenHint --value=0

# Activate debug mode, this is required for OIDC to work without HTTPS
php occ config:system:set debug --value true

# Allow local "remote" servers for this docker-based development setup
php occ config:system:set allow_local_remote_servers --value true --type bool
